export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';

export const FETCH_STABILITY_DATA = 'FETCH_STABILITY_DATA';
export const FETCH_RELATED_SITES = 'FETCH_RELATED_SITES';
export const FETCH_HTTPCODES_CLASS = 'FETCH_HTTPCODES_CLASS';
export const FETCH_HTTPCODES_CLASS_QUESTIONS = 'FETCH_HTTPCODES_CLASS_QUESTIONS';
export const FETCH_HTTPCODES = 'FETCH_HTTPCODES';
export const FETCH_HTTPCODES_QUESTIONS = 'FETCH_HTTPCODES_QUESTIONS';

export const ADD_QUESTIONAIRE = 'ADD_QUESTIONAIRE';
export const UNDO_ANSWER_QUESTIONAIRE = 'UNDO_ANSWER_QUESTIONAIRE';
